---
title: "The Importance of Replicability"
author: "Alexander Dean"
subtitle: "Recitation Period 2"
institute: "Vanderbilt University"
email: "alexander.r.dean@vanderbilt.edu"
date: today
format: 
  revealjs:
    theme: dark
    footer: "Alexander Dean (Vanderbilt University)"
    slide-number: true
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    self-contained-math: true
    incremental: false
    self-contained: true
    citations-hover: true
    fragments: true
    scrollable: false
    transition: fade
    reference-location: document
fontsize: 32px
editor: source
---

# Introductory Spiel

## What We Will Cover Today
1. Some best practices for having replicable work
2. A replication activity

## Why You Should Pay Attention to Today's Recitation
1. Having replicable work gives you integrity in the discipline
2. Publishing data, codebooks, etc. are increasingly the norm for both experimental and observational work in political science

# Introducing Replication

## Replication Exercise

- Form yourselves into groups of 2
- Spend 30 minutes on the exercise together and report back with your results (we'll regroup at ~2:35)

## Debriefing

- What did you think?
- What results did you find?

## So what do you need for replication?
1. What would you have wanted to better replicate the article's findings?

. . . 

- Raw data
- Cleaned data
- Codebook
- **A clear description of data wrangling, data cleaning, and data analysis**

# Questions?